Vagrant.configure("2") do |config|

    config.vm.box = "debian/bookworm64"
    config.vm.box_check_update = false
  
    config.vm.define "arabiaiS" do |server|
      server.vm.hostname = "arabiaiS"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = 2048 # previously 1024: becuase kubectl take to much to execute
        vb.cpus = 2 # previously 1
        vb.name = "arabiaiS-p2"
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end
      server.vm.provision "shell", path: "scripts/server.sh"
    end
  
  end