#!/bin/bash

# Update package manager and install curl (needed to download K3s)
apt-get update -y
apt-get install -y curl

# Wait for the node token to be available
# The server VM must finish installing K3s first and copy the token
# to the shared /vagrant directory before the agent can join
echo "Waiting for server node token..."
while [ ! -f /vagrant/scripts/node-token ]; do
  sleep 2
done
echo "Node token found."

# Read the token generated by the server
TOKEN=$(cat /vagrant/scripts/node-token)

# Install K3s in agent mode
# K3S_URL: points the agent to the server's Kubernetes API (port 6443)
# K3S_TOKEN: the shared secret that proves this agent is authorized to join
# --node-ip: advertise on the private network, not the NAT interface
# --flannel-iface: use the private network interface for pod-to-pod traffic
curl -sfL https://get.k3s.io | K3S_URL="https://192.168.56.110:6443" \
  K3S_TOKEN="$TOKEN" \
  INSTALL_K3S_EXEC="agent \
    --node-ip 192.168.56.111 \
    --flannel-iface eth1" sh -

echo "K3s agent installed and joining cluster."